name: envia_com
description: E-Commerce de Prueba
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.6.5
  flutter_secure_storage: ^8.0.0
  reactive_forms: ^14.3.0
  http: ^0.13.5
  loading_animation_widget: ^1.2.0+4
  animated_text_kit: ^4.2.2
  darq: ^1.2.1
  searchbar_animation: ^0.0.4
  shimmer: ^2.0.0
  sqflite: ^2.2.8+4
  font_awesome_flutter: ^10.4.0
  flutter_switch: ^0.3.2
  mask_text_input_formatter: ^2.4.0
  local_auth: ^2.1.6
  google_fonts: ^4.0.4
  pointycastle: ^3.7.3
  basic_utils: ^5.5.4
  encrypt: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
